POST https://node-do-zero-6rph.onrender.com/videos
Content-Type: application/json

{"title": "Video node",
"description":"Esse é o vídeo 01",
"duration":180}

###

GET https://node-do-zero-6rph.onrender.com/videos

###

PUT https://node-do-zero-6rph.onrender.com/videos/
Content-Type: application/json

{"title": "Video 02",
"description":"Esse é o vídeo 01",
"duration":180}

###

DELETE https://node-do-zero-6rph.onrender.com/videos/